
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/integrations/http
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  # https://peyanski.com/home-assistant-remote-access/
  ip_ban_enabled: true
  login_attempts_threshold: 5

homeassistant:
  # https://www.home-assistant.io/docs/authentication/providers/
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8
  external_url: !secret ha_external_url
  # If tts isn't working in your media players (and on a Google device at most you get a bloop), 
  #   then the problem is most likely down to SSL. If you're using SSL in HA make sure that your 
  #   external_url is correctly set, and that internal_url matches it. Alternatively set base_url 
  #   in the tts integration to your external SSL URL.
  internal_url: !secret ha_external_url

# Text to speech
tts:
  - platform: google_translate

# https://www.home-assistant.io/integrations/counter/
counter:
  ezan_counter:
    initial: 0
    step: 1


# Required for ios app
ios:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

