
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key 
  base_url: !secret http_base_url

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8

# Update duckdns record in case public IP changes
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token


# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: islamic_prayer_times
  - platform: crimereports
    name: crime
    radius: 1000

counter:
  ezan_counter:
    initial: 0
    step: 1

notify:
  - name: facebook
    platform: facebook
    page_access_token: !secret facebook_page_access_code

# Required for ios app
ios:

device_tracker:
  - platform: traccar
    host: !secret traccar_host
    username: !secret traccar_username
    password: !secret traccar_password


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
